### ISSUE TITLE
Change `engines.node` in package.json to something like `>=16` with respect to Svelte 4 version

### ISSUE THREAD

**Issue by himuspz** [BrianMitchL/svelte-compare-image#10]
Right now, I am unable to use this package in AWS Amplify due to the `engines.node` version to be quite high (~18)

**Comment by BrianMitchL** [comment]
Good call, even with Node 16 being EOL in a month, there are likely several people and environments still using it.

**Comment by BrianMitchL** [comment]
This has been released with [v2.0.2](https://github.com/BrianMitchL/svelte-compare-image/releases/tag/v2.0.2), thanks for reporting the issue!

**Comment by himuspz** [comment]
Thanks a lot! Thanks for the package as well! This helped us pass AWS Amplify CI/CD
